spring:
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: jdbc:mysql://localhost:3306/pj6_plus
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

### sql 로그 확인하기위해
#logging:
#  level:
#    root: info
#    org.hibernate.SQL: debug

server:
  tomcat:
    max-http-form-post-size: 100MB

jwt:
  secret:
    key: dXJ2N3pBNEp0S0R5V2FhT0tHbFZqNnB5QXJ2QnN2YVZpQ1J3bFZ0RkJ5U1d1eE5nZk1jS1R0N0o4QkE=
